Load packages 
```{r}
library(lattice)
library(ggplot2)
library(caret)
library(kernlab)
library(rattle)
library(corrplot)
```

## Data Processing

```{r}
traincsv <- read.csv("pml-training.csv")
```


```{r}
testcsv <- read.csv("pml-testing.csv")
```
```{r}
dim(traincsv)
dim(testcsv)
```

##Cleaning Data

```{r}
traincsv <- traincsv[,colMeans(is.na(traincsv)) < .9] #removing mostly na columns
traincsv <- traincsv[,-c(1:7)] #removing metadata which is irrelevant to the outcome

nvz <- nearZeroVar(traincsv)
traincsv <- traincsv[,-nvz]
dim(traincsv)
```

```{r}
inTrain <- createDataPartition(y=traincsv$classe, p=0.7, list=F)
train <- traincsv[inTrain,]
valid <- traincsv[-inTrain,]
```


Creating & testing Model

```{r}
control <- trainControl(method="cv", number=3, verboseIter=F)
```
```{r}
mod_trees <- train(classe~., data=train, method="rpart", trControl = control, tuneLength = 5)
fancyRpartPlot(mod_trees$finalModel)
```
Predictions

```{r}
pred_trees <- predict(mod_trees, valid)
cmtrees <- confusionMatrix(pred_trees, factor(valid$classe))
cmtrees
```

##Random Forest

```{r}
mod_rf <- train(classe~., data=train, method="rf", trControl = control, tuneLength = 5)

pred_rf <- predict(mod_rf, valid)
cmrf <- confusionMatrix(pred_rf, factor(valid$classe))
cmrf
```

## GBM

```{r}

mod_gbm <- train(classe~., data=train, method="gbm", trControl = control, tuneLength = 5, verbose = F)

pred_gbm <- predict(mod_gbm, valid)
cmgbm <- confusionMatrix(pred_gbm, factor(valid$classe))
cmgbm
```


##SVM

```{r}
mod_svm <- train(classe~., data=train, method="svmLinear", trControl = control, tuneLength = 5, verbose = F)

pred_svm <- predict(mod_svm, valid)
cmsvm <- confusionMatrix(pred_svm, factor(valid$classe))
cmsvm
```


##Prediction on  test data 
```{r}
pred <- predict(mod_rf, testcsv)
print(pred)
```


##Correlation 

```{r}
corrPlot <- cor(train[, -length(names(train))])
corrplot(corrPlot, method="color")
```

```{r}
plot(mod_trees)
```
```{r}
plot(mod_rf)
```
```{r}
plot(mod_gbm)
```



